"use client";

import { Geist, Geist_Mono } from "next/font/google";
import { useState } from "react";

import "./globals.css";
import { styles } from "./assets/styles";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import { SidebarProvider } from "./context/SidebarContext";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const [sidebarCollapsed, setSidebarCollapsed] = useState(false);

	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
		>
			<body className={styles.layout.root}>
				<Navbar />
				<SidebarProvider
					sidebarCollapsed={sidebarCollapsed}
					setSidebarCollapsed={setSidebarCollapsed}
				>
					<Sidebar />
					{children}
				</SidebarProvider>
			</body>
		</html>
	);
}
